definitions:
  steps:
    - step: &staticAnalysis
        name: "Sonarqube step for Java Apps"
        oidc: true
        image: sonarqube:lts
        script:
          # Show role is base ec2 runnerr
          - echo $(aws sts get-caller-identity)
          - echo "Sonarqube analysis goes here."

    - step: &unitTesting
        name: "Unit testing step for Java Apps"
        oidc: true
        image: maven:3.8.3-openjdk-17
        script:
          # Show role is base ec2 runnerr
          - echo $(aws sts get-caller-identity)
          - echo "Unit testing goes here"

    - step: &compile
        name: "Compilation step for Java Apps"
        image: maven:3.8.3-openjdk-17
        services:
          - docker
        artifacts:
          - "**.jar"
        script:
          - echo "'mvn clean package' goes here"

    - step: &deploy
        name: "Deploy step for Java Apps"
        oidc: true
        image: bitnami/kubectl:latest
        script:
          # Show role is base ec2 runnerr
          - echo "'kubectl apply -f deploy_manifest.yml' goes here"


pipelines:
  branches:
    develop:
      - step:
          <<: *compile
      - step:
          <<: *deploy

    release:
      - step:
          <<: *compile
      - step:
          <<: *deploy

    master:
      - step:
          <<: *compile
      - step:
          <<: *deploy

  pull-requests:
    develop:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    release:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    master:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    feature/**:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    bugfix/**:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    hotfix/**:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile
