definitions:
  steps:
    - step: &staticAnalysis
        name: "Sonarqube step"
        image: sonarqube:lts
        script:
          - echo "Sonarqube analysis goes here."

    - step: &unitTesting
        name: "Unit testing step"
        image: maven:3.8.3-openjdk-17
        script:
          - echo "'mvn test' goes here"

    - step: &compile
        name: "Compilation step"
        image: maven:3.8.3-openjdk-17
        artifacts:
          - "**.jar"
        script:
          - echo "'mvn clean package -DskipTests=true' goes here"

    - step: &tagDevelop
        name: "Develop tagging step"
        image: alpine/git
        script:
          - echo "commit hash id + timestamp git tag cmd goes here"

    - step: &tagReleaseCandidate
        name: "Release candidate tagging step"
        image: alpine/git
        script:
          - echo "semver git tag cmd wit '-rc' suffix goes here"

    - step: &tagSemver
        name: "Semver tagging step"
        image: alpine/git
        script:
          - echo "semver git tag cmd with suffix goes here"

    - step: &containerization
        name: "Containerization step"
        image: maven:3.8.3-openjdk-17
        services:
          - docker
        script:
          - echo "Docker containerization goes here"

    - step: &pushToCodeArtifact
        name: "Push to code artifact step"
        image: amazon/aws-cli
        script:
          - echo "Push of container to AWS CodeArtifact goes here"

    - step: &deploy
        name: "Deploy step"
        image: bitnami/kubectl:latest
        script:
          - echo "AWS EKS deployment goes here"

    - step: &postDeployCheck
        name: "Post deploy check step"
        image: bitnami/kubectl:latest
        script:
          - echo "Post-deploy check goes here"

    - step: &downstreamDevelop
        name: "Downstream to develop branch step"
        image: alpine/git
        script:
          - echo "Downstream to develop goes here"

    - step: &downstreamSit
        name: "Downstream to sit branch step"
        image: alpine/git
        script:
          - echo "Downstream to sit goes here"

    - step: &downstreamRelease
        name: "Downstream to release branch step"
        image: alpine/git
        script:
          - echo "Downstream to release goes here"

pipelines:
  branches:
    develop:
      - step:
          <<: *compile
      - step:
          <<: *containerization
      - step:
          <<: *tagDevelop
      - step:
          <<: *pushToCodeArtifact
      - step:
          <<: *deploy
      - step:
          <<: *postDeployCheck

    sit:
      - step:
          <<: *compile
      - step:
          <<: *containerization
      - step:
          <<: *tagSemver
      - step:
          <<: *pushToCodeArtifact
      - step:
          <<: *deploy
      - step:
          <<: *postDeployCheck
      - step:
          <<: *downstreamDevelop

    release:
      - step:
          <<: *tagReleaseCandidate

    master:
      - step:
          <<: *compile
      - step:
          <<: *containerization
      - step:
          <<: *tagSemver
      - step:
          <<: *pushToCodeArtifact
      - step:
          <<: *deploy
      - step:
          <<: *postDeployCheck
      - step:
          <<: *downstreamSit
      - step:
          <<: *downstreamRelease
      - step:
          <<: *downstreamDevelop

  pull-requests:
    develop:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    sit:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    release:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    master:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    feature/**:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    bugfix/**:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile

    hotfix/**:
      - step:
          <<: *staticAnalysis
      - step:
          <<: *unitTesting
      - step:
          <<: *compile
